djnd/djnd/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.templatetags.static import static
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from home.views import AgrumentByDateRedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url=static("favicons/favicon.ico"))),
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # this is a hack because we cant use the wagtail page view since it does not support periods in the url
    re_path(
        r"agrument/(?P<day>\d{1,2})\.(?P<month>\d{1,2})\.(?P<year>\d{4})/$",
        AgrumentByDateRedirectView.as_view(),
        name="agrument-by-date",
    ),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Translatable URLs
# These will be available under a language code prefix. For example /en/search/
urlpatterns += i18n_patterns(
    path("trgovina/", include("shop.urls")),
    path("api/", include("home.urls")),
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

djnd/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("activities/", views.ActivityView.as_view(), name="activities"),
    path(
        "activities-homepage/",
        views.ActivityHomepageView.as_view(),
        name="activities-homepage",
    ),
    path("newsletters/", views.NewsletterListView.as_view(), name="newsletters"),
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
]

djnd/home/models/snippets.py
from django import forms
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import TranslatableMixin
from wagtail.search import index


class ActivityCategory(TranslatableMixin, models.Model):
    name = models.TextField()
    icon = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    order = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.name

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Kategorija"
        verbose_name_plural = "Kategorije"
        ordering = ["order"]


class ActivityProject(TranslatableMixin, models.Model):
    name = models.TextField()
    icon = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    order = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.name

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Projekt"
        verbose_name_plural = "Projekti"
        ordering = ["order"]


class Activity(index.Indexed, TranslatableMixin, models.Model):
    title = models.TextField()
    link = models.URLField(verbose_name="Zunanja povezava", null=True, blank=True)
    page = models.ForeignKey(
        "wagtailcore.Page",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        verbose_name="Povezava na podstran",
    )
    description = models.TextField(blank=True)
    image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    pillar_page = models.ManyToManyField("home.PillarPage", blank=True)
    category = models.ManyToManyField(ActivityCategory, blank=True)
    project = models.ManyToManyField(ActivityProject, blank=True)
    date = models.DateField(null=True, blank=True)
    note = RichTextField(null=True, blank=True)
    promoted = models.BooleanField(default=False)

    panels = [
        FieldPanel("title"),
        FieldPanel("link"),
        FieldPanel("page"),
        FieldPanel("description"),
        FieldPanel("image"),
        FieldPanel("pillar_page", widget=forms.CheckboxSelectMultiple),
        FieldPanel("category", widget=forms.CheckboxSelectMultiple),
        FieldPanel("project", widget=forms.CheckboxSelectMultiple),
        FieldPanel("date"),
        FieldPanel("note"),
        FieldPanel("promoted"),
    ]

    search_fields = [
        index.SearchField("title"),
        index.AutocompleteField("title"),
        index.FilterField("locale_id"),
    ]

    def __str__(self) -> str:
        return self.title

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Aktivnost"
        verbose_name_plural = "Aktivnosti"


class TeamMemberCategory(TranslatableMixin, models.Model):
    name = models.TextField()

    def __str__(self) -> str:
        return self.name

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Vloga člana ekipe"
        verbose_name_plural = "Vloge članov ekipe"


class TeamMember(index.Indexed, TranslatableMixin, models.Model):
    name = models.TextField()
    email = models.TextField(blank=True)
    role = models.TextField(blank=True)
    image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    category = models.ManyToManyField(TeamMemberCategory, blank=True)

    panels = [
        FieldPanel("name"),
        FieldPanel("email"),
        FieldPanel("role"),
        FieldPanel("image"),
        FieldPanel("category", widget=forms.CheckboxSelectMultiple),
    ]

    search_fields = [
        index.SearchField("name"),
        index.AutocompleteField("name"),
        index.FilterField("locale_id"),
    ]

    def __str__(self) -> str:
        return self.name

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Član ekipe"
        verbose_name_plural = "Člani ekipe"


class Promoted(TranslatableMixin, models.Model):
    title = models.TextField(
        blank=True,
        verbose_name="Naslov",
        help_text="Če so polja prazna in obstaja Aktivnost, se uporabijo podatki Aktivnosti",
    )
    description = models.CharField(
        blank=True,
        verbose_name="Opis",
    )
    image = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        verbose_name="Slika",
    )
    link = models.URLField(
        blank=True,
        verbose_name="Povezava",
    )
    activity = models.ForeignKey(
        Activity,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        verbose_name="Aktivnost",
    )

    def __str__(self) -> str:
        if self.activity:
            return self.title if self.title else self.activity.title
        else:
            return self.title

    class Meta(TranslatableMixin.Meta):
        verbose_name = "Izpostavljeno"
        verbose_name_plural = "Izpostavljeno"

djnd/home/forms.py
from django import forms
from django.template.defaultfilters import slugify
from wagtail.admin.forms.models import WagtailAdminModelForm
from wagtail.admin.forms.pages import WagtailAdminPageForm
from wagtail.models import Locale

from .models.pages import PillarPage
from .models.snippets import ActivityCategory, ActivityProject, TeamMemberCategory

#
# ADMIN FORMS
#


# SNIPPET FORMS
class ActivityAdminModelForm(WagtailAdminModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # filter querysets based on locale
        sl = Locale.objects.get(language_code="sl")
        self.fields["pillar_page"].queryset = PillarPage.objects.filter(locale=sl)
        self.fields["category"].queryset = ActivityCategory.objects.filter(locale=sl)
        self.fields["project"].queryset = ActivityProject.objects.filter(locale=sl)


class TeamMemberAdminModelForm(WagtailAdminModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # filter querysets based on locale
        sl = Locale.objects.get(language_code="sl")
        self.fields["category"].queryset = TeamMemberCategory.objects.filter(locale=sl)


# PAGE FORMS
class ActivityTagPageAdminPageForm(WagtailAdminPageForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # filter querysets based on locale
        sl = Locale.objects.get(language_code="sl")
        self.fields["pillar_page"].queryset = PillarPage.objects.filter(locale=sl)
        self.fields["category"].queryset = ActivityCategory.objects.filter(locale=sl)
        self.fields["project"].queryset = ActivityProject.objects.filter(locale=sl)


class BlogPageAdminPageForm(ActivityTagPageAdminPageForm):
    pass


class NewsletterPageAdminPageForm(ActivityTagPageAdminPageForm):
    pass


#
# FORMS
#

FIELD_TO_MODEL = {
    "pillars": PillarPage,
    "categories": ActivityCategory,
    "projects": ActivityProject,
}

FIELD_TO_NAME = {
    "pillars": "title",
    "categories": "name",
    "projects": "name",
}


class OurWorkForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.locale = kwargs.pop("locale")

        # map slugs to ids in query
        if args and args[0]:
            querydict_ids = self.map_query_dict_slugs(args[0])
            args = (querydict_ids,) + args[1:]

        super().__init__(*args, **kwargs)

        # filter querysets based on locale
        for field_name, Model in FIELD_TO_MODEL.items():
            self.fields[field_name].queryset = Model.objects.filter(locale=self.locale)

    pillars = forms.ModelMultipleChoiceField(
        required=False,
        queryset=PillarPage.objects,
        widget=forms.CheckboxSelectMultiple(attrs={"class": ""}),
    )
    categories = forms.ModelMultipleChoiceField(
        required=False,
        queryset=ActivityCategory.objects,
        widget=forms.CheckboxSelectMultiple(attrs={"class": ""}),
    )
    projects = forms.ModelMultipleChoiceField(
        required=False,
        queryset=ActivityProject.objects,
        widget=forms.CheckboxSelectMultiple(attrs={"class": ""}),
    )
    promoted = forms.BooleanField(required=False)

    def map_query_dict_slugs(self, querydict):
        querydict = querydict.copy()  # original is immutable
        for key in querydict:
            values = self.map_slugs_to_ids(key, querydict.getlist(key))
            querydict.setlist(key, values)
        return querydict

    def map_slugs_to_ids(self, field_name, slugs):
        if not slugs:
            return []
        if field_name not in FIELD_TO_MODEL:
            return slugs

        Model = FIELD_TO_MODEL[field_name]
        name = FIELD_TO_NAME[field_name]
        objects = Model.objects.all()
        slug_to_id = {
            slugify(getattr(obj, name)): str(
                obj.get_translation_or_none(self.locale).id
            )
            for obj in objects
            if obj.get_translation_or_none(self.locale)
        }
        return [slug_to_id.get(slug, slug) for slug in slugs]

    def filter_activities(self, activities):
        if self.is_valid():
            pillars = self.cleaned_data["pillars"]
            categories = self.cleaned_data["categories"]
            projects = self.cleaned_data["projects"]
            promoted = self.cleaned_data["promoted"]

            if pillars:
                activities = activities.filter(pillar_page__in=pillars)

            if categories:
                activities = activities.filter(category__in=categories)

            if projects:
                activities = activities.filter(project__in=projects)

            if promoted:
                activities = activities.filter(promoted=True)

        return activities.distinct()

djnd/home/views.py
import datetime

from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import TemplateView, View
from wagtail.models import Locale, Site

from .models.pages import BlogListingPage, BlogPage, NewsletterListPage, NewsletterPage
from .pagination import get_filtered_activities, paginate_limit_offset


def _activity_pagination_context(request, for_homepage=False):
    offset = int(request.GET.get("offset", 0))

    activities, _ = get_filtered_activities(request, for_homepage=for_homepage)
    activities = paginate_limit_offset(activities, limit=12, offset=offset)

    return {
        "page_obj": activities,
        "activities": activities.object_list,
    }


class ActivityView(TemplateView):
    template_name = "home/activities.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            _activity_pagination_context(
                self.request,
            )
        )
        return context


class ActivityHomepageView(TemplateView):
    template_name = "home/activities-homepage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            _activity_pagination_context(
                self.request,
                for_homepage=True,
            )
        )
        return context


def _subpage_pagination_context(request, context_name, ParentPageModel, SubPageModel):
    parent = int(request.GET.get("parent", 0))
    parent_page = ParentPageModel.objects.filter(pk=parent).first()

    offset = int(request.GET.get("offset", 0))
    locale = Locale.get_active()

    newsletters = (
        SubPageModel.objects.child_of(parent_page)
        .filter(locale=locale)
        .live()
        .order_by("-published_at", "-first_published_at", "pk")
    )
    newsletters = paginate_limit_offset(newsletters, limit=12, offset=offset)

    return {
        "page_obj": newsletters,
        context_name: newsletters.object_list,
    }


class NewsletterListView(TemplateView):
    template_name = "home/newsletters.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            _subpage_pagination_context(
                self.request,
                "newsletters",
                NewsletterListPage,
                NewsletterPage,
            )
        )
        return context


class BlogListView(TemplateView):
    template_name = "home/blogs.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            _subpage_pagination_context(
                self.request,
                "blogs",
                BlogListingPage,
                BlogPage,
            )
        )
        return context


# ------------


class AgrumentByDateRedirectView(View):
    def get(self, request, day, month, year):
        date = datetime.date(int(year), int(month), int(day))

        locale = Locale.objects.get(language_code="sl")
        site = Site.objects.get(is_default_site=True)
        root_page = site.root_page.get_translation(locale)
        page = root_page.get_children().filter(slug="agrument").first()

        if page is None:
            raise Http404

        blog = (
            BlogPage.objects.child_of(page)
            .filter(locale=locale, published_at=date)
            .live()
            .order_by("-first_published_at", "pk")
            .first()
        )

        if blog is None:
            raise Http404

        return redirect(blog.get_url())

djnd/home/templates/home/activities-homepage.html
{% load static i18n %}

{% for activity in activities %}

  {% include 'home/partials/activity.html' with activity=activity %}

  {% if forloop.last and page_obj.has_next %}
    {% include 'home/partials/loader.html' with next_page_offset=page_obj.next_page_offset view='activities-homepage' hidden=True %}
    <div class="absolute bottom-0 left-0 right-0 mx-auto text-center">
      <button type="button" onclick="loadMoreOnHomePage(this)" class="inline-flex text-md font-medium hover:font-bold theme-color-{{ button_color }} tertiary-button group xl-max:text-smd">
        <span>{% translate "Več aktivnosti" %}</span><img class="w-4 ml-4 -mb-0.5 group-hover:animate-arrow-hover-down" src="{% static "img/noun-arrow-down-1434311.svg" %}" alt="">
      </button>
    </div>
  {% endif %}

{% endfor %}

djnd/home/templates/home/activities.html
{% for activity in activities %}

  {% include 'home/partials/activity.html' with activity=activity %}

  {% if forloop.last and page_obj.has_next %}
    {% include 'home/partials/loader.html' with next_page_offset=page_obj.next_page_offset view='activities' %}
  {% endif %}

{% endfor %}

djnd/home/templates/home/blogs.html
{% for blog in blogs %}

  {% include "home/partials/blog_activity.html" with activity=blog %}

  {% if forloop.last and page_obj.has_next and not without_loader %}
    {% include 'home/partials/loader.html' with next_page_offset=page_obj.next_page_offset view='blogs' %}
  {% endif %}

{% endfor %}

djnd/home/templates/home/home_page.html
{% extends "wrapper.html" %}
{% load static wagtailcore_tags wagtailimages_tags i18n djnd_extras %}

{% block body_class %}template-homepage theme-color-{{ page.color }}{% endblock %}

{% block content %}
<div>
  <div class="border-b border-dark last:border-b-0 bg-white">
    <div class="flex gap-10 max-w-[1280px] mx-auto px-14 pt-20 lg-max:block sm-max:px-6 sm-max:pt-8">
      <div class="basis-8/12">
        <h1 class="mb-6 last:mb-0 text-5xl font-semibold xl-max:text-2xl">{{ page.title }}</h1>
        {% if page.introduction %}
        <div class="text-xl/[3rem] font-normal xl-max:text-2md" data-introduction="true">
          {{ page.introduction|richtext }}
        </div>
        {% endif %}
      </div>
      <div class="basis-4/12 sm-max:pt-8">
        <h2 class="mt-5 text-center font-semibold text-xl xl-max:text-lg/[1.15]">{{ page.focus_areas_title }}</h2>
        <div class="my-6">
          {% for focus_area in page.focus_areas %}
          {% cycle 'one' 'two' 'three' 'four' as focus_cycle silent %}
          {% if focus_area.value.url or focus_area.value.page %}
          <a href="{% if focus_area.value.page %}{% pageurl focus_area.value.page %}{% else %}{{ focus_area.value.url }}{% endif %}" class="group">
          {% endif %}
          <div data-linked-sentence="{{ focus_area.value.linked_sentence }}" data-color="{{ focus_area.value.color }}" class="
            theme-color-{{ focus_area.value.color }}
            relative flex items-center gap-4 mt-4 px-8 py-7 shadow-dark shadow-[0px_0px_0px_1px] bg-th-primary
            {% if focus_cycle == 'one' %}
            -rotate-2 -translate-x-3
            {% elif focus_cycle == 'two' %}
            rotate-3 translate-x-3
            {% elif focus_cycle == 'three' %}
            rotate-[-0.5deg] -translate-x-3
            {% elif focus_cycle == 'four' %}
            rotate-[4deg] translate-x-3
            {% endif %}
            transition-all duration-150 [@media(hover:hover)]:group-hover:scale-105 [@media(hover:hover)]:group-hover:shadow-[0px_0px_0px_2px] [@media(hover:hover)]:group-hover:z-10
          ">
            <div class="w-14 shrink-0">
              {% image focus_area.value.image fill-112x112 class="aspect-square" %}
            </div>
            <div class="flex-grow font-medium text-lg/none xl-max:text-md">
              {{ focus_area.value.name }}
            </div>
            <img class="w-5 ml-2 -mb-0.5 [@media(hover:hover)]:group-hover:animate-arrow-hover" src="{% static "img/noun-arrow-right-1434311.svg" %}" alt="">
          </div>
          {% if focus_area.value.url or focus_area.value.page %}
          </a>
          <a name="tmp-focus-{{ forloop.counter }}"></a>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  {% for block in page.modules %}
  <div class="border-b border-dark last:border-b-0">
    {% include_block block %}
  </div>
  {% endfor %}

  <a name="activities"></a>
  <div class="max-w-[1280px] mx-auto px-14 pt-16 pb-20 sm-max:block sm-max:px-6 sm-max:pt-8 sm-max:pb-10">
    <div class="flex flex-wrap justify-between mb-6">
      <h2 class="mb-2 text-2xl font-semibold xl-max:text-lg">{% translate "Zadnje aktivnosti" %}</h2>
      {% if settings.home.GeneralSettings.our_work_page %}
      {% wagtail_site as current_site %}
      <form id="our-work-form" action="{% pageurl current_site.root_page.localized %}#activities" method="get" class="flex items-center ml-auto">

        <div class="me-3 sm-max:hidden">
          <input type="radio" name="filter" value="all" class="peer hidden" id="id_all" onchange="filterOurWork()" {% if request.GET.filter == 'all' or not request.GET.filter %}checked{% endif %}>
          <label
            for="id_all"
            class="
              inline-flex items-center px-4 pt-2.5 pb-3 shadow-dark shadow-[0px_0px_0px_1px] rounded-full text-md/none cursor-pointer
              lg-max:px-3 lg-max:py-1.5 lg-max:text-sm/none
              peer-checked:bg-th-primary peer-checked:shadow-[0px_0px_0px_2px]
              transition-all duration-150 hover:scale-105 hover:shadow-[0px_0px_0px_2px] hover:bg-th-primary
            "
          >
            {% translate "Vse" %}
          </label>
        </div>

        <div class="me-3 sm-max:hidden">
          <input type="radio" name="filter" value="promoted" class="peer hidden" id="id_promoted" onchange="filterOurWork()" {% if request.GET.filter == 'promoted' %}checked{% endif %}>
          <label
            for="id_promoted"
            class="
              inline-flex items-center px-4 pt-2.5 pb-3 shadow-dark shadow-[0px_0px_0px_1px] rounded-full text-md/none cursor-pointer
              lg-max:px-3 lg-max:py-1.5 lg-max:text-sm/none
              peer-checked:bg-th-primary peer-checked:shadow-[0px_0px_0px_2px]
              transition-all duration-150 hover:scale-105 hover:shadow-[0px_0px_0px_2px] hover:bg-th-primary
            "
          >
            <img class="h-[20px] w-auto me-2 lg-max:h-[14px]" src="{% static 'img/filter-izpostavljeno.png' %}" alt="">
            {% translate "Izpostavljeno" %}
          </label>
        </div>

        <div class="me-3 sm-max:hidden">
          <input type="radio" name="filter" value="newsletter" class="peer hidden" id="id_newsletter" onchange="filterOurWork()" {% if request.GET.filter == 'newsletter' %}checked{% endif %}>
          <label
            for="id_newsletter"
            class="
              inline-flex items-center px-4 pt-2.5 pb-3 shadow-dark shadow-[0px_0px_0px_1px] rounded-full text-md/none cursor-pointer
              lg-max:px-3 lg-max:py-1.5 lg-max:text-sm/none
              peer-checked:bg-th-primary peer-checked:shadow-[0px_0px_0px_2px]
              transition-all duration-150 hover:scale-105 hover:shadow-[0px_0px_0px_2px] hover:bg-th-primary
            "
          >
            <img class="h-[20px] w-auto me-2 lg-max:h-[14px]" src="{% static 'img/filter-obcasnik.png' %}" alt="">
            {% translate "Občasnik" %}
          </label>
        </div>

        <a href="{% pageurl settings.home.GeneralSettings.our_work_page.localized %}" class="self-center ml-1 hover:font-semibold group">
          <span class="inline-block min-w-[56px] text-center underline">{% translate "Vsi filtri" %}</span><img class="inline-block w-3 ml-2 -mt-1 group-hover:animate-arrow-hover" src="{% static "img/noun-arrow-right-1434311.svg" %}" alt="">
        </a>

      </form>
      {% endif %}

    </div>
    <div class="grid grid-cols-3 gap-4 pb-[80px] relative lg-max:grid-cols-2 sm-max:grid-cols-1">
      {% for activity in activities %}
        {% include 'home/partials/activity.html' with activity=activity %}

        {% if forloop.counter == 3 %}
          {% include 'home/partials/newsletter_card.html' with id=forloop.counter %}
        {% endif %}

        {% if forloop.counter == 7 %}
          {% include 'home/partials/support_card.html' %}
        {% endif %}

        {% if forloop.last and page_obj.has_next %}
          {% include 'home/partials/loader.html' with next_page_offset=page_obj.next_page_offset view='activities-homepage' hidden=True %}
          <div class="absolute bottom-0 left-0 right-0 mx-auto text-center">
            <button type="button" onclick="loadMoreOnHomePage(this)" class="inline-flex text-md font-medium hover:font-bold theme-color-{{ button_color }} tertiary-button group xl-max:text-smd">
              <span>{% translate "Več aktivnosti" %}</span><img class="w-4 ml-4 -mb-0.5 group-hover:animate-arrow-hover-down" src="{% static "img/noun-arrow-down-1434311.svg" %}" alt="">
            </button>
          </div>
        {% endif %}
      {% endfor %}
    </div>

  </div>

</div>
{% endblock content %}

djnd/home/templates/home/our_work_page.html
{% extends "wrapper.html" %}
{% load i18n static wagtailcore_tags wagtailimages_tags djnd_extras %}

{% block body_class %}template-ourworkpage theme-color-{{ page.color }}{% endblock %}

{% block content %}

<div class="max-w-[1280px] mx-auto px-14 py-16 sm-max:px-6 sm-max:py-8">
  <h1 class="mb-6 text-4xl font-semibold xl-max:text-2xl">{{ page.title }}</h1>

  <form id="our-work-form" action="{% pageurl page.localized %}" method="get" class="mb-8">

    <div class="mb-2">
      <p class="font-mono">{% translate "Filtriraj po tematskih sklopih" %}</p>
      <div id="id_pillars" class="mb-2 -mx-6 -mt-2">
        <div class="py-3 overflow-x-auto thin-scroll">
          <div class="flex gap-2 px-6 w-max">
            {% for pillar in pillars %}
            {% include "home/partials/activity_filter.html" with filter=pillar filter_name="pillars" filter_values=form.pillars.value %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="mb-2">
      <p class="font-mono">{% translate "Filtriraj po kategorijah" %}</p>
      <div id="id_categories" class="mb-2 -mx-6 -mt-2">
        <div class="py-3 overflow-x-auto thin-scroll">
          <div class="flex gap-2 px-6 w-max">
            {% for category in categories %}
            {% include "home/partials/activity_filter.html" with filter=category filter_name="categories" filter_values=form.categories.value %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="mb-2">
      <p class="font-mono">{% translate "Filtriraj po projektih" %}</p>
      <div id="id_projects" class="mb-2 -mx-6 -mt-2">
        <div class="py-3 overflow-x-auto thin-scroll">
          <div class="flex gap-2 px-6 w-max">
            {% translate "Izpostavljeno" as filter_title %}
            {% include "home/partials/activity_filter.html" with filter_title=filter_title filter_name="promoted" filter_value=form.promoted.value filter_image='img/filter-izpostavljeno.png' %}
            {% for project in projects %}
            {% include "home/partials/activity_filter.html" with filter=project filter_name="projects" filter_values=form.projects.value %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

  </form>

  <div class="grid grid-cols-3 gap-4 lg-max:grid-cols-2 sm-max:grid-cols-1">
    {% for activity in activities %}

      {% include 'home/partials/activity.html' with activity=activity %}

      {% if forloop.counter == 3 %}
        {% include 'home/partials/newsletter_card.html' with id=forloop.counter %}
      {% endif %}

      {% if forloop.counter == 7 %}
        {% include 'home/partials/support_card.html' %}
      {% endif %}

      {% if forloop.last and page_obj.has_next %}
        {% include 'home/partials/loader.html' with next_page_offset=page_obj.next_page_offset view='activities' %}
      {% endif %}

    {% endfor %}
  </div>
</div>

{% endblock content %}